compute_environment: LOCAL_MACHINE
debug: false 
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false

## For FSDP -- incompatible with 4 or 8 bit quantization
# compute_environment: LOCAL_MACHINE                                                                                                                                           
# debug: false                                                                                                                                                                 
# distributed_type: FSDP
# downcast_bf16: 'no'
# fsdp_config:
#   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#   fsdp_backward_prefetch_policy: BACKWARD_PRE
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_forward_prefetch: false
#   fsdp_offload_params: true
#   fsdp_sharding_strategy: 1
#   fsdp_state_dict_type: SHARDED_STATE_DICT
#   fsdp_sync_module_states: true
#   fsdp_use_orig_params: true
# machine_rank: 0
# main_training_function: main
# mixed_precision: bf16
# num_machines: 2
# num_processes: 2
# rdzv_backend: static
# same_network: true
# use_cpu: false